---
- hosts: all
  become: yes
  tasks:
  - name: restart all packages
    service: name={{ item }} state=restarted
    with_items:
    - nova-api
    - nova-consoleauth
    - nova-scheduler
    - nova-conductor
    - nova-novncproxy
